const ShopActionTypes = {
    UPDATE_COLLECTIONS : 'UPDATE_COLLECTIONS',
    FETCH_COLLECTIONS_START: "FETCH_COLLECTIONS_START",
    FETCH_COLLECTIONS_SUCCESS: "FETCH_COLLECTIONS_SUCCESS",
    FETCH_COLLECTIONS_FILURE: "FETCH_COLLECTIONS_FILURE"
}

export default ShopActionTypes